### ISSUE TITLE
CSS validation errors

### ISSUE THREAD

**Issue by flecktarn121** [InigoGutierrez/mainpage#1]
Hi,
I have taken the responsibility (expected by anyone who calls himself _software engineer_ ) of checking the [standard validity](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fgithub.com%2FInigoGutierrez%2Fmainpage%2Fblob%2Fmaster%2Fcss%2Fstyle.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) of the CSS. 
This is unacceptable. Great geniuses of our time, like [Mr. Cueva](https://pbs.twimg.com/profile_images/1321516787/image.jpg) or [Sir Tim Berners Lee](https://www.w3.org/People/Berners-Lee/), have preached about standardization for a reason.
Consider making a correction.

**Comment by InigoGutierrez** [comment]
I'm sorry, but you made a wrong move here. You asked for validation of the GitHub page showing the file and not the file contents themselves! If you pass the actual contents of the file, you will see there are no mistakes found, which proves I am the smartest CSSer that has ever lived.
